server:
  port: 8081

spring:
  application:
    name: userservice

  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: shan
    password: password123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true