server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/users/**

            - id: document-service
              uri: lb://DOCUMENT-SERVICE
              predicates:
                - Path=/api/v1/documents/**