server:
  port: 8086

spring:
  application:
    name: ai-service

  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: shan
    password: password123

  jpa:
    hibernate:
      ddl-auto: validate

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: ai-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.shan.aidoc.commonevents
        spring.json.value.default.type: com.shan.aidoc.commonevents.DocumentCreatedEvent
        spring.json.use.type.headers: false

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.2
      embedding:
        options:
          model: nomic-embed-text

    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 768

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka